### ISSUE TITLE
Implement the server for Python requests

### ISSUE THREAD

**Issue by emregoynugur** [OpenMined/OpenMined#10]
**User Scenario:** Server functionality (ClientObject.cs and ServerObject.cs files) required for handling requests from Python scripts/programs should be implemented. 

The architecture for this component has to be discussed. i.e. a simple event router, a web server, micro-service architecture etc.

**Acceptance Criteria:**

TBD

**Comment by iamtrask** [comment]
This is a great issue! We basically need the most efficient (in terms of both dev time and runtime) method possible for controlling our C# backend from our Python front end - just spitballing here - compressed JSON seems like a reasonable place to start - sent over ZMQ

**Comment by iamtrask** [comment]
The second answer in this one seems promising - https://stackoverflow.com/questions/6620165/how-can-i-parse-json-with-c

dynamic stuff = JsonConvert.DeserializeObject("{ 'Name': 'Jon Smith', 'Address': { 'City': 'New York', 'State': 'NY' }, 'Age': 42 }");

string name = stuff.Name;
string address = stuff.Address.City;

**Comment by iamtrask** [comment]
Note to self - always check Unity's own documentation first - https://docs.unity3d.com/Manual/JSONSerialization.html

**Comment by iamtrask** [comment]
Got Unity's example code working there - now my mind is wondering where we should put the parsing functionality. I'm inclined to think we should put it as close to the actual functionality as possible. Like - logic for parsing commands interacting with the FloatTensor object should be managed by the FloatTensor object - that way when you want to add a new function - you only have to interact with one place.

**Comment by iamtrask** [comment]
I stopped here: https://github.com/OpenMined/OpenMined/pull/11

**Comment by iamtrask** [comment]
Picking this up again today - it's hard to make progress on any of the other tickets without having the end user experience available (the client)

**Comment by iamtrask** [comment]
I'm going to start by swapping out our current functionality with a JSON interpreter just so that we are using/experimenting with something that's both more flexible and easier to read. To that end, I'll be creating a "Command" class which is what gets serialized. 

After sleeping on it, I'm also going to implement command logic (translating messages -> API calls) inside the class to which it pertains.... aka... when i want to add two tensors together, the logic for translating the JSON command into calling the right function will actually be INSIDE the Tensor class itself. I think this makes the most sense from a ease-of-development standpoint with minimal costs to performance complexity.

**Comment by emregoynugur** [comment]
I think command pattern is the right way to do it.  All the operations we want to implement can inherit from that base class.

Another question is how do we handle the interprocess communication (Python-Unity)? If IPC is going to happen only locally, then I read that named pipes are the way to go. Otherwise, I guess we should stick to the TCP sockets like you already did.

**Comment by iamtrask** [comment]
@gavinuhma and I had an hour long call last night walking through different architectures - we landed on the "Asyncronous Request-Reply Server" as a great interim option - we then realized that this was already implemented in ServerObject with a hookup to Python. So, the fortunate part is that we got to just inherit the example code. At a later date we'll need to add a security layer but it was nice to get to have something working relatively easily so we can focus instead on the API calls - presumably we can swap out the actual communication layer layer

**Comment by iamtrask** [comment]
To start, I'm assuming SyftController has a global list of FloatTensor objects which it keeps in memory. When we create a new SyftTensor object, it just appends one to the list and returns its index (which is by extension the pointer to that object which python can use). To that end, I'm thinking that we can call the constructor to create a new FloatTensor with the following JSON 

```
d = {}
d['objectType'] = 'FloatTensor'
d['objectIndex'] = -1.
d['functionCall'] = 'FloatTensor'
d['functionParams'] = list()

param = {}
param['type'] = 'float[]'
param['values'] = [0.,1.,2.,3.,4.,5.]

d['functionParams'].append(param)
```

**Comment by iamtrask** [comment]
I'm going to get a demo working and then try to hook it up to the various functions we already have for FloatTensor
