### ISSUE TITLE
L2C5 - ModuleNotfoundError: 'syft.core.adp.entity'

### ISSUE THREAD

**Issue by yannik1015** [OpenMined/openmined#219]
## Description
In lesson 2 chapter 5 the example code does not work as the second example already fails finding the module 'syft.core.adp.entity'

## How to Reproduce
Follow the instructions from lesson 2.

## Information
 - OS: Debian 11
 - Language Version: python 3.9.13
 - Package Manager Version: conda 4.12.0

**Comment by austinabell** [comment]
I also ran into this issue, was there some way to resolve it?
