### ISSUE TITLE
Unable to move stuck at course Foundations of Private Computation on 96.2% 

### ISSUE THREAD

**Issue by anilpatil-securityarchitect** [OpenMined/openmined#231]
## Unable to move stuck at course Foundations of Private Computation on 96.2% 
A clear and concise description of the bug.

## How to Reproduce
1. Go to '[...](https://courses.openmined.org/users/dashboard)'
2. Click on '[...](https://courses.openmined.org/courses/foundations-of-private-computation/370facdd-9d7e-4507-81eb-d63a6491f10a)'
3. Scroll down to '[...](https://courses.openmined.org/courses/foundations-of-private-computation/370facdd-9d7e-4507-81eb-d63a6491f10a)'

## Screenshots
![2024-05-09 21_02_48-Greenshot](https://github.com/OpenMined/openmined/assets/31351722/368a2d53-dc46-4799-8be8-9465f29dc27f)

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

## Additional Context
![2024-05-09 21_02_14-Greenshot](https://github.com/OpenMined/openmined/assets/31351722/0f8a6974-e80f-4fc5-bd84-69a89995b764)
![2024-05-09 21_01_31-Greenshot](https://github.com/OpenMined/openmined/assets/31351722/6ee18043-62da-4178-96dd-bdbb7cc2a6af)

**Comment by tcp** [comment]
Hey Anil -- did you submit a bug report? If so, I can check it out tomorrow.

**Comment by anilpatil-securityarchitect** [comment]
I have submit bug screenshot and I want resolve ASAP bcz I was bug submit through mail but nothing any progress since 1.6 years. Resolve my problem ASAP. I will finish my course.

**Comment by anilpatil-securityarchitect** [comment]
Waiting for problem to resolve...

**Comment by anilpatil-securityarchitect** [comment]
Awaiting.....

**Comment by anilpatil-securityarchitect** [comment]
Awaiting..............

**Comment by anilpatil-securityarchitect** [comment]
I request you to solve my course error during completion. I stuck in this course since 1 and half year.

I request take my problem seriously and solve my course bug/error/problem ASAP.

**Comment by anilpatil-securityarchitect** [comment]
Course Bug  Link [Here](https://courses.openmined.org/courses/foundations-of-private-computation/370facdd-9d7e-4507-81eb-d63a6491f10a)

**Comment by anilpatil-securityarchitect** [comment]
Till date Im unable to move in this course......Does anybody here......I request you to look on my issue somebody in Opnemined......please look on......

**Comment by anilpatil-securityarchitect** [comment]
Awaiting................

**Comment by anilpatil-securityarchitect** [comment]
I request you to, resolve my problem on 1st priority basis.....

**Comment by anilpatil-securityarchitect** [comment]
Till date 05-19-2024 page show error[](https://courses.openmined.org/courses/foundations-of-private-computation/370facdd-9d7e-4507-81eb-d63a6491f10a)

Pfa screenshot: 
![2024-05-19 10_59_51-Greenshot](https://github.com/OpenMined/openmined/assets/31351722/e8c30180-1e2f-4c8f-b9e7-93272097bbd3)

I request the anyone from team of OpenMined please look this issue seriuosly , resolve course issue ASAP.

**Comment by anilpatil-securityarchitect** [comment]
I request does anybody is here?  for listening my issue?.................

**Comment by anilpatil-securityarchitect** [comment]
Kindly resolve my problem ASAP.

**Comment by anilpatil-securityarchitect** [comment]
Does any body a true person can take it my problem seriously in @OpenMined #231

**Comment by anilpatil-securityarchitect** [comment]
Whom is solve my problem....any body at least reply?

**Comment by tcp** [comment]
Hey @anilpatil-securityarchitect, I have seen your request.

I'll get back to you as soon as when a fix is rolled out.

**Comment by anilpatil-securityarchitect** [comment]
Please urgent......

**Comment by anilpatil-securityarchitect** [comment]
Issue  till date is pending
![2024-06-03 19_44_42-Greenshot](https://github.com/OpenMined/openmined/assets/31351722/2e3020cc-b3fc-4dcd-b821-55653ae3f778)

**Comment by tcp** [comment]
Fixed.

**Comment by anilpatil-securityarchitect** [comment]
Thank you so much!.
