### ISSUE TITLE
Unique Index For Users

### ISSUE THREAD

**Issue by emregoynugur** [OpenMined/OpenMined#31]
**User Story:**  Server should assign a unique id to each attached user (u_id).

We can use Router-Dealer example of NetMQ to differentiate clients. http://netmq.readthedocs.io/en/latest/router-dealer/

**Acceptance Criteria:**

- Server should keep a structure that allows us to search users/clients with their u_ids.

**Comment by iamtrask** [comment]
I believe @gavinuhma has implemented this functionality.

**Comment by emregoynugur** [comment]
Yes :) waiting for him to commit. Current implementation gets client ids but it doesn’t store them.

We can also consider a secure authorization mechanism like using Json Web Tokens, but no rush :)

**Comment by iamtrask** [comment]
Something worth considering - the number of client users into a single Mine is probably going to be quite small. From clients like PySyft - i'd be surprised if a mine ever had more than 1 or 2. However, mine->mine communication will probably be quite a few more to facilitate the training.

**Comment by iamtrask** [comment]
but concurrently i'd be surprised if there were more than a dozen or so - simply because the local GPU is unlikely to process more models that that at one time
