### ISSUE TITLE
Unique Index For Tensors

### ISSUE THREAD

**Issue by emregoynugur** [OpenMined/OpenMined#33]
**User Story:**  Server should assign to each tensor (t_id) a client creates. We could use these ids in the command class and to manage data access.  This id could simply be an object counter for each user.

**Acceptance Criteria:**

- Server should keep a structure that allows us to search users with their u_ids and tensors inside the user space. An example structure could be: UserTable<u_id, TensorTable>, TensorTable <t_id, Tensor>

**Comment by iamtrask** [comment]
This is a killer issue - a side note worth mentioning is that in the final api (PySyft or syftj.s) we want all this to be abstracted away so that it feels like they're working with normal tensors.
