### ISSUE TITLE
Add IntTensor integration tests and examples

### ISSUE THREAD

**Issue by xnutsive** [OpenMined/OpenMined#344]
## Context
As a developer who is new to the project, I'd like a way to make sure my pull request doesn't break things. To do that, I want a suite of tests to run after I implemented a feature. 

We have some integration tests in `integration/tests.py` using PyTest (cc @bendecoste), but that only tests `FloatTensor`. 

We also have a notebook that explores OpenMined tensor API `notebooks/tests/Test Tensor Function Implementations` that tests _some_ functions, but definitely not all of them. 

I suggest we keep the test suite up to date, but maybe decide if we want to have both tests and the notebook, or keep just one of them. I understand that we should (and @bendecoste is working on that) run test on Travis, and therefore we need to keep and update the tests. 

Whether we need the notebook with examples of the API calls is up to discussion. 

### Acceptance Criteria:

# Checklist:
- [x] `integration/tests.py` has tests for all implemented `FloatTensor` and `IntTensor` methods on CPU
- [ ] `integration/tests.py` has tests for all implemented `FloatTensor` and `IntTensor` methods on GPU
- [ ] The examples notebook has all the methods tested and described.

**Comment by Agent007** [comment]
IntTensor tests are definitely needed. Does it make more sense to move the tests to PySyft since we're calling the Python code?

**Comment by xnutsive** [comment]
@Agent007, I agree, it makes more sense to keep python tests with the python lib. 

I'll take this. 

@iamtrask @gavinuhma want me to also move the tests to PySyft repo?

**Comment by justin1121** [comment]
Hey, putting the integration tests in the OpenMined repo was discussed here https://github.com/OpenMined/OpenMined/pull/144. I agree with what @bendecoste was saying.

**Comment by xnutsive** [comment]
Got it, sounds reasonable. 

I'll start with just adding some IntTensor tests.
