### ISSUE TITLE
Improve contribution guidelines

### ISSUE THREAD

**Issue by xnutsive** [OpenMined/OpenMined#345]
### Context

I'm new to the project and it was a bit unclear what exactly should I check for before creating a pull request with some code updates. What test suites to run, what parts of projects to update. 

We came up with the list: 

```
@gavin @trask so when we want to implement a new tensor operation, we need to: 
1. Comment that I’m taking the op
2. Write a test in openmined/notebooks/ notebook to show how to use the op from PySyft
3. Write an intergration test in OpenMined/integration/tests.py
4. Write a test in OpenMined Unity code
5. Implement pysyft code
6. Implement Unity code (+GPU code if required)
7. Make sure Unity tests pass
8. Make sure Integration tests pass
9. Make sure Notebook tests pass
10. Wrap things up and do a pull request. 
```

I'm working on clarifying what PySyft integration tests and examples notebook should look like here (#344). Once we come up with a decision on tests and examples, I can add the list to the contribution guidelines here: https://github.com/OpenMined/Docs/blob/master/contributing/guidelines.md with specific instructions on which tests to write and how to run them. 

Any suggestions, @iamtrask, @gavinuhma?

**Comment by bharathgs** [comment]
@xnutsive this sounds good to me

**Comment by xnutsive** [comment]
Done and merged, we can close that I think.
