### ISSUE TITLE
Refactor: SyftController.cs to create new tensor objects

### ISSUE THREAD

**Issue by emregoynugur** [OpenMined/OpenMined#46]
Current implementations of tensor operations are in FloatTensor and they modify the calling object. This modifies the tensor of a Syft client. e.g a + b changes a. 

We can implement a wrapper in the math package which SyftController can use and that wrapper could create new tensors as needed.

We can also consider removing all these ops out of FloatTensor.

**Comment by emregoynugur** [comment]
If we are going to keep the ops in FloatTensor, we can simply modify the existing operators to create a new tensor as well.

**Comment by Floev** [comment]
@emregoynugur good to close?

**Comment by emregoynugur** [comment]
Indeeed
