### ISSUE TITLE
Implement Base Tensor Type and Tests

### ISSUE THREAD

**Issue by emregoynugur** [OpenMined/OpenMined#5]
**User Story:** We want to port the packages in PySyft to the new Unity project. TensorBase class seems like the minimal requirement to port syft.he syft.mpc packages and math.py file.

**Acceptance Criteria:**

- [ ] Implement tests as they are in the Python implementation

- [ ] Implement the core structure of TensorBase class and supplementary methods like "_ensure_ndarray" in tensor.py

- [ ] All tests should pass

**Comment by emregoynugur** [comment]
I started working on this issue. I guess we should talk about the following:

- The primitive data, which is suitable for encryption operations. 
- Should we support more than 2 dimensions? This could really simplify the implementation.

**Comment by emregoynugur** [comment]
I guess we need 3D tensors for Conv Nets etc anyway. So nevermind.

**Comment by iamtrask** [comment]
Just saw this! I have some strong opinions on this one actually. The underlying data structure should always be a vector (just an array) - and we should have a second array that stores the dimensionality. In this way - we can reshape the number of rows and columns without moving any data around.

**Comment by iamtrask** [comment]
The basic FloatTensor I implemented already in this project stores data this way as well.

**Comment by iamtrask** [comment]
does that make sense?

**Comment by emregoynugur** [comment]
Yes, it does. I am actually taking your FloatTensor implementation as a reference. Also, I am looking into how other frameworks implemented tensors in C and C++.
