### ISSUE TITLE
Incorporating some Functional Programming Concepts

### ISSUE THREAD

**Issue by galletti94** [OpenMined/OpenMined#51]
Hi Everyone,

After looking through the FloatTensor.Ops.cs file and trying to add a few functions, I was thinking that incorporating some functional programming ideas could help increase productivity. For example building a handful of higher order functions could help make our code more adaptable to changes. To illustrate this idea a bit I have written a few such functions here: 

https://github.com/galletti94/OpenMined/blob/master/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs

The idea is that if we now want to add Homomorphic Encryption, parallelism, exceptions, etc to all the tensor functions, we need only change the main combinators (map(), filter(), fold() etc). And if we change our minds about whether each function should mutate the input or produce a new tensor, we can easily change that too.

What do you guys think of this approach? Let me know your thoughts!

**Comment by galletti94** [comment]
That's a great question! It is true that with functional programming often comes adverse effects on performance. After doing some research on C#, I think these effects are minimal with the way we wrote our functions. Let me try and walk through the Map() example. We have the following:

       `public FloatTensor Map(Func<float, float> f)
        {
            FloatTensor output = new FloatTensor (this.shape, dataOnGpu);
            if (dataOnGpu) {
	        return this;   //just a placeholder
            } else {
                for (int i = 0; i < size; i++) {
		    output.data [i] = f(this.Data [i]);
		}
		return output;
            }
        }`

And we declare:

       `public FloatTensor ScalarMultiplication(float scalar)
        {
            return this.Map((x) => x*scalar);
        }`

The lambda function (x) => x*scalar will be bound to the variable f of the Map function. It looks like the only time this binding happens is when the function is called. Here because we are not making a recursive call to map (which would be the typically FP way of writing such a function) this binding only happens once. So it seems like the only overhead we will experience from this approach should not propagate through the for loop. I will run some tests just in case :)

**Comment by diegoalejogm** [comment]
@emregoynugur Shouldn't' this be closed?

@galletti94 We tested the performance with both approaches (functional and non-functional), and it was much faster when using non-functional programming (probably there's a better term for this).

**Comment by galletti94** [comment]
Good to know - thanks for letting me know! Ill close this issue now
