### ISSUE TITLE
Implement math operations (math.py) in Unity

### ISSUE THREAD

**Issue by emregoynugur** [OpenMined/OpenMined#7]
**User Story:** We should implement the functionality in math.py using shaders. We could also consider having CPU implementations. 

This issue depends on Tensor Base #5 . We can split this one issue into multiple tasks (one for each math operator.)

**Acceptance Criteria:**

- [ ] Implement all tests related to math.py in Unity

- [ ] Implement math functions

- [ ] All math.py tests should pass

- [ ] All Tensor Base tests using math functionality should pass

**Comment by iamtrask** [comment]
+1 - only detail to add is that the functions should automatically check to see where the data is stored and run the appropriate code (HLSL or local CPU code)
